apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: futr-za-jutr
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: futr-za-jutr
    newName: rg.fr-par.scw.cloud/djnd/futr-za-jutr
    newTag: 'd74ccefb40a4005118287b1f1dec71b3e29f40ac'
