apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: futr-za-jutr
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: futr-za-jutr
    newName: rg.fr-par.scw.cloud/djnd/futr-za-jutr
    newTag: '9242eb6ff76d36a6ef33ec229468bb076ffb9283'
